### ISSUE TITLE
数据库那一步怎么处理

### ISSUE THREAD

**Issue by zhiqiuchn** [yumusb/pinqiong.net#1]
我是用的宝塔搭建的，然后，数据库也配置了，但是我付钱后，钱可以成功到账，但是网页没有提示成功，还是挂着的，下面的记录也没有

**Comment by yumusb** [comment]
那你应该回调的问题。

**Comment by zhouguangyou1994** [comment]
貌似出问题了，扶贫记录不会更新了，希望作者更新一下

**Comment by yumusb** [comment]
> 貌似出问题了，扶贫记录不会更新了，希望作者更新一下

什么时候 pinqiong.net 不能更新，说明真的出问题。
